name: Deploy FRONT

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Prepare known_hosts (verify if fingerprint provided)
        shell: bash
        run: |
          set -euo pipefail
          HOST="${{ vars.DEPLOY_HOST || '75.119.135.119' }}"
          PORT="${{ vars.DEPLOY_PORT || '22' }}"
          EXPECT="${{ vars.DEPLOY_HOST_FINGERPRINT || '' }}"

          ACTUAL="$(ssh-keyscan -p "$PORT" -t ed25519 "$HOST" 2>/dev/null \
                   | ssh-keygen -lf - | awk '{print $2}')"
          echo "Host ed25519 fingerprint: $ACTUAL"

          # اگر EXPECT پر باشد، باید دقیقاً برابر باشد؛ اگر خالی بود صرفاً KnownHosts را می‌نویسیم
          if [[ -n "$EXPECT" && "$ACTUAL" != "$EXPECT" ]]; then
            echo "❌ Fingerprint mismatch"
            echo "Expected: $EXPECT"
            echo "Actual:   $ACTUAL"
            exit 1
          fi

          mkdir -p ~/.ssh
          ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.DEPLOY_HOST || '75.119.135.119' }}
          username: ${{ vars.DEPLOY_USER || 'deploy' }}
          port: ${{ vars.DEPLOY_PORT || '22' }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          command_timeout: 30m
          script: |
            /usr/local/bin/deploy-celex-front
